### ISSUE TITLE
Feature Request: Rudimentary Bazel IJ plugin support.

### ISSUE THREAD

**Issue by hsyed** [pubref/rules_kotlin#38]
[https://github.com/bazelbuild/intellij/issues/148](issue)

@pcj The bazel IJ plugin works fairly without any config, it does wipe the Kotlin configuration on each workspace sync. It would be great to contribute basic Kotlin support to the IJ plugin codebase.

I'll have a gander at the task but I don't have the bandwidth at the moment. I can help test.

**Comment by pcj** [comment]
LInk https://github.com/bazelbuild/intellij/issues/148

**Comment by hsyed** [comment]
[I have a wip pr open on the bazel ij repo](https://github.com/bazelbuild/intellij/pull/157).

**Comment by hsyed** [comment]
[I opened a new PR as per the suggestions](https://github.com/bazelbuild/intellij/pull/166). It seems to work.

**Comment by hsyed** [comment]
implemented in my fork, out of scope for these rules.
